CI: false
CIPrior: false
CMF: true
FusionEarly: true
ImputMode: CGMM
ImputMode2: MICE
Resample: false
SFD: true
alpha_cc: 1
alpha_vs: 0.6
backbone: TextResNet
batch_size: 1024
bestmodel: ./weight/best_model.pth
bs_test: 512
cache_clip: ./weight/clip_cn_vit-b-16.pt
cache_dir: ./cached_data/
cc_sim_thresh: 0.8
data_path_clean: ./data/CleanData.txt
data_path_dirty: ./data/TriageData(raw).txt
data_quality: dirty
dynamic_coverage: 0.98
embed_dim: 128
filter: false
grade: false
hidden_dim: 64
in_dim: 768
label_correct: false
length: 1000000
log_path: ./result/dirty_phase\TextResNet_CGMM_vsEmbed_SFD_FusEarly8_CMF_bert\46\training_log.txt
loss: ''
lr: 0.001
lr_cc: 0.0001
lr_vs: 0.001
lstm_layers: 1
min_count: 20
mode: test
n_comp: 8
n_comps: 2
ndc: 3
nec: 3
num_epochs: 100
num_heads: 8
output_dir: ./result/
patience: 10
rand_seed: 46
se: 2
stage0_epochs: 6
stage1_epochs: 6
stopword_path: ./StopWords/stopword.txt
text_encoder: bert
text_length: 20
threshold: 0.5
use_vs_mask: false
vsEmbed: true
vs_mask_rate: 0.1
